### ISSUE TITLE
SdkClientException: Unable to execute HTTP request

### ISSUE THREAD

**Issue by zhs41** [mathworks-ref-arch/matlab-aws-s3#8]
I have previously successfully used this package for accessing data on a drive using AWS S3. However, I recently got a similar drive but am puzzled when getting the following error after doing exactly the same steps:

Java exception occurred:
com.amazonaws.SdkClientException: Unable to execute HTTP request: "endpoint name"
at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1216)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1162)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:811)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:779)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:753)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:713)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:695)
      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:559)
      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:539)
      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5453)
      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5400)
      at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1524)
Caused by: java.net.UnknownHostException:  "endpoint name"
      at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
      at java.net.InetAddress.getAllByName(InetAddress.java:1193)
      at java.net.InetAddress.getAllByName(InetAddress.java:1127)
      at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
      at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
      at shaded.org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
      at shaded.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:498)
      at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
      at com.amazonaws.http.conn.$Proxy28.connect(Unknown Source)
      at shaded.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
      at shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
      at shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
      at shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
      at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
      at shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
      at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1343)
      at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1154)
      ... 10 more

Error in aws.s3.Client/load (line 83)
    obj.getObject(bucketName, objectName, tmpName);

**Comment by brownemi** [comment]
Hi zhs41,

Apologies for the slow response over the recent holiday period.

Can you confirm if:
1. The bucket name you are providing is just the bucket name and not something like s3://mybucket or a https URL?
2. Do you have a HomeDirectory/.aws/config file that defines a region value or another definition of the region value elsewhere on the provider chain, see Documentation/Authentication.md for details.
3. Is the bucket in an AWS China region?
4. Can you call non-load methods e.g.: x = s3.listBuckets() and is so do you see the bucket name in the result?

Please do NOT share the bucket name or credentials here publicly in logs etc.

**Comment by zhs41** [comment]
Hello,


  1.
I am only providing the bucket name
  2.
I am trying to implement this package in a linux HPC, and the aws drive I got is one of the OSN drive that uses aws s3, so I think I do not have a config file un /.aws/config. I am using environment variable approach to specify the region and keys. This works for a previous OSN but not this time. I asked the technical support and is suggested to add addressing_style": "path" to the AWS credentials ini. However, again I do not have a clue how to find this file.
  3.
No
  4.
This returns an empty table.

Thanks
________________________________

**Comment by brownemi** [comment]
Okay, I think it may be simplest to debug this in person. Can I ask that you email mwlab@mathworks.com with some time suggestions in the coming days, if we could overlap with Irish zone and if possible US eastern time. I'll then get back to you with a Teams link.

**Comment by brownemi** [comment]
A call was held to diagnose this issue.
The endpoint was a non AWS S3 endpoint.
The solution was to add the `s3.pathStyleAccessEnabled = true;` line as shown below and described in <https://github.com/mathworks-ref-arch/matlab-aws-s3/blob/master/Documentation/GettingStarted.md>

```
s3 = aws.s3.Client();
s3.endpointURI = matlab.net.URI('https://mycustomendpoint.example.com');
s3.pathStyleAccessEnabled = true;
s3.initialize();
```
